feat(server): add import-lesson, still not finished with corner case
CLDXiang/fdpink pull request #12
Opened 2021-12-27 15:05 UTC by SunflowerAries

## ✨ 工作描述

## 🍀 给 Reviewer 的辅助信息

- 

## 🛠️ 对项目配置的改动

- 

## 👀 更多

- 

## ✅ 检查清单

- [ ] 建立 lesson 等一系列表单的 migration
- [ ] import-lesson 的实现
- [ ] import-lesson corner case 的处理

2022-01-01 16:53 UTC, CLDXiang requested changes
补充一下描述

2022-01-01 16:53 UTC, CLDXiang commented on README.md
> +# Welcome to fdpink
这里确认一下是不是又被改回 CRLF 了

2022-01-01 16:53 UTC, CLDXiang commented on server/scripts/import_lesson.sh
> +done
最后要留一个空行

2022-01-01 16:53 UTC, CLDXiang commented on server/src/lecture/port.service.ts
> +  knownDup2 = new Map<string, InstructorInfo>()
这一部分 case by case 的这种处理是为什么？

2022-01-01 17:12 UTC, ichn-hu requested changes

2022-01-01 17:12 UTC, ichn-hu commented on server/src/lecture/dto/import-lesson.dto.ts
> +  @IsNumber()
应该还加上 range 检查

2022-01-01 17:12 UTC, ichn-hu commented on server/src/lecture/port.service.ts
> +  knownDup2 = new Map<string, InstructorInfo>()
应该是课程编号不同，本质上是同一门课，一堂开给不同院系的课？感觉前期可能没必要考虑这个细节，会增加处理逻辑的复杂度，不过已经加上了也没别的坏处。

2022-01-01 17:12 UTC, ichn-hu commented on server/src/lecture/port.service.ts
> +  knownDup2 = new Map<string, InstructorInfo>()
哦，其实还是有坏处的，后续维护成本很高的说……？

2022-01-01 17:12 UTC, ichn-hu commented on server/src/lecture/views/instructor.ts
> +@ViewEntity({
牛的，才知道这种做法，用 view 来简化逻辑

2022-01-03 05:11 UTC, SunflowerAries commented on server/src/lecture/port.service.ts
> +  knownDup2 = new Map<string, InstructorInfo>()
每学期就添加一些 corner case，因为大部分在前面已经覆盖了，所以不超过 10 分钟？

2022-01-03 05:24 UTC, merged